import { Component } from '@angular/core';import { RouterOutlet,RouterLink } from '@angular/router';
@Component({
  selector:'app-website-layout',
  standalone:true,
  imports:[RouterOutlet,RouterLink],
  template:`<header class="site-header"><nav class="container nav"><a routerLink="/" class="logo"><span class="logo-icon">✦</span> AuraSalon Enterprise</a><div class="links"><a (click)="scrollTo('features')">Features</a><a (click)="scrollTo('modules')">Modules</a><a (click)="scrollTo('ai')">AI</a><a (click)="scrollTo('business-types')">Business Types</a></div><div class="nav-actions"><a routerLink="/login" class="btn btn-outline">Login</a><a routerLink="/book-online" class="btn btn-primary">Book Online</a></div><button class="mobile-toggle" (click)="mobileOpen=!mobileOpen" aria-label="Menu">☰</button></nav><div class="mobile-nav" [class.open]="mobileOpen"><a (click)="scrollTo('features');mobileOpen=false">Features</a><a (click)="scrollTo('modules');mobileOpen=false">Modules</a><a (click)="scrollTo('ai');mobileOpen=false">AI</a><a (click)="scrollTo('business-types');mobileOpen=false">Business Types</a><a routerLink="/login" (click)="mobileOpen=false">Login</a><a routerLink="/book-online" (click)="mobileOpen=false">Book Online</a></div></header><router-outlet></router-outlet><footer class="footer"><div class="container footer-inner"><div class="footer-brand"><h3>AuraSalon Enterprise</h3><p>Complete AI-powered salon, spa, barber & beauty business operating system. Manage every aspect of your beauty business from one modern platform.</p></div><div class="footer-links"><div class="footer-col"><h4>Product</h4><a (click)="scrollTo('features')">Features</a><a (click)="scrollTo('modules')">Modules</a><a (click)="scrollTo('ai')">AI</a></div><div class="footer-col"><h4>Business Types</h4><a (click)="scrollTo('business-types')">Hair Salons</a><a (click)="scrollTo('business-types')">Spas</a><a (click)="scrollTo('business-types')">Barbers</a></div><div class="footer-col"><h4>Quick Links</h4><a routerLink="/login">Login</a><a routerLink="/book-online">Book Online</a><a (click)="scrollTo('features')">About</a></div></div></div><div class="container footer-bottom"><span>&copy; 2026 AuraSalon Enterprise. All rights reserved.</span></div></footer>`,
  styles:[`.site-header{position:sticky;top:0;z-index:100;background:rgba(255,255,255,.98);border-bottom:1px solid var(--border);backdrop-filter:blur(12px)}.nav{height:72px;display:flex;align-items:center;justify-content:space-between}.logo{font-weight:800;font-size:18px;display:flex;align-items:center;gap:8px;letter-spacing:-.02em}.logo-icon{color:var(--gold);font-size:22px}.links{display:flex;gap:28px;font-size:14px;font-weight:500}.links a{cursor:pointer;transition:color .2s}.links a:hover{color:var(--gold)}.nav-actions{display:flex;gap:10px;align-items:center}.btn-outline{border:1px solid var(--border);border-radius:12px;padding:9px 20px;font-weight:600;font-size:14px;color:var(--black);transition:all .2s}.btn-outline:hover{border-color:var(--black)}.mobile-toggle{display:none;background:none;border:none;font-size:24px;cursor:pointer;padding:8px}.mobile-nav{display:none;position:absolute;top:72px;left:0;right:0;background:white;border-bottom:1px solid var(--border);padding:16px 24px;flex-direction:column;gap:12px;z-index:99}.mobile-nav.open{display:flex}.mobile-nav a{cursor:pointer;padding:10px 0;font-weight:500;font-size:15px;border-bottom:1px solid var(--soft)}.footer{background:var(--black);color:white;padding:64px 0 0}.footer-inner{display:grid;grid-template-columns:2fr 3fr;gap:64px;padding-bottom:48px}.footer-brand h3{font-size:20px;font-weight:800;letter-spacing:-.02em;margin:0 0 12px}.footer-brand p{color:#9ca3af;font-size:14px;line-height:1.7;max-width:380px;margin:0}.footer-links{display:grid;grid-template-columns:repeat(3,1fr);gap:32px}.footer-col h4{font-size:13px;font-weight:700;text-transform:uppercase;letter-spacing:.06em;color:var(--gold);margin:0 0 16px}.footer-col a{display:block;color:#9ca3af;font-size:14px;padding:6px 0;cursor:pointer;transition:color .2s}.footer-col a:hover{color:white}.footer-bottom{border-top:1px solid #222;padding:20px 0;font-size:13px;color:#6b7280}@media(max-width:768px){.links{display:none}.nav-actions{display:none}.mobile-toggle{display:block}.footer-inner{grid-template-columns:1fr;gap:40px}.footer-links{grid-template-columns:1fr 1fr}.footer-brand p{max-width:100%}}@media(min-width:769px){.mobile-nav{display:none!important}}`]}
)
export class WebsiteLayoutComponent{
  mobileOpen = false;
  scrollTo(id:string){
    this.mobileOpen = false;
    const el = document.getElementById(id);
    if(el) el.scrollIntoView({behavior:'smooth'});
  }
}
