import { Component } from '@angular/core';import { RouterLink } from '@angular/router';
@Component({
  selector:'app-home',
  standalone:true,
  imports:[RouterLink],
  template:`
<!-- Hero -->
<section class="hero"><div class="container hero-grid"><div><div class="hero-badge">AI-Powered Beauty Business OS</div><h1>Complete AI-powered salon, spa, barber & beauty business operating system.</h1><p class="hero-sub">Manage bookings, POS, staff, clients, inventory, marketing, reports, payments, memberships and AI insights from one modern platform.</p><div class="hero-trust">Built for salons, spas, barbers, beauty clinics and multi-branch chains.</div><div class="hero-actions"><a routerLink="/login" class="btn btn-primary btn-lg">Login to Dashboard</a><a routerLink="/book-online" class="btn btn-secondary btn-lg">Book Online Demo</a></div></div><div class="hero-visual"><div class="dash-preview"><div class="dash-header"><span class="dash-dot"></span><span class="dash-dot"></span><span class="dash-dot"></span><span class="dash-label">Dashboard Preview</span></div><div class="dash-grid"><div class="dash-card"><div class="dash-card-icon bookings-icon"></div><div class="dash-card-body"><span class="dash-card-label">Today Bookings</span><strong class="dash-card-value">24</strong><span class="dash-card-change up">+12%</span></div></div><div class="dash-card"><div class="dash-card-icon revenue-icon"></div><div class="dash-card-body"><span class="dash-card-label">Revenue</span><strong class="dash-card-value">₹48,500</strong><span class="dash-card-change up">+8%</span></div></div><div class="dash-card"><div class="dash-card-icon staff-icon"></div><div class="dash-card-body"><span class="dash-card-label">Staff Utilization</span><strong class="dash-card-value">87%</strong><span class="dash-card-change up">+5%</span></div></div><div class="dash-card"><div class="dash-card-icon ai-icon"></div><div class="dash-card-body"><span class="dash-card-label">AI Insight</span><strong class="dash-card-value">↑12%</strong><span class="dash-card-text">Retention up</span></div></div><div class="dash-card"><div class="dash-card-icon retention-icon"></div><div class="dash-card-body"><span class="dash-card-label">Retention Rate</span><strong class="dash-card-value">94%</strong><span class="dash-card-change up">+3%</span></div></div></div><div class="dash-bar"><div class="dash-bar-item"><span>Revenue</span><div class="dash-bar-track"><div class="dash-bar-fill" style="width:78%"></div></div></div><div class="dash-bar-item"><span>Bookings</span><div class="dash-bar-track"><div class="dash-bar-fill" style="width:65%"></div></div></div></div></div></div></div></section>

<!-- Partners / Trust Bar -->
<section class="trust-bar"><div class="container"><div class="trust-logos"><span>Trusted by 500+ beauty businesses</span><span>4.9/5 Rating</span><span>99.9% Uptime</span><span>ISO 27001</span><span>24/7 Support</span></div></div></section>

<!-- Features -->
<section class="section" id="features"><div class="container"><div class="section-head"><h2>Everything you need to run your beauty business</h2><p>Complete suite of tools designed for modern salons, spas and barbershops.</p></div><div class="features-grid"><div class="feature-card"><div class="feature-marker" style="background:#0b0b0b"></div><h3>Smart Calendar & Bookings</h3><p>Online booking, real-time calendar sync, automated reminders, and smart scheduling that eliminates no-shows.</p></div><div class="feature-card"><div class="feature-marker" style="background:#d4af37"></div><h3>POS, Billing & Invoices</h3><p>Fast point of sale with split payments, digital invoices, tax support, and integrated payment gateway.</p></div><div class="feature-card"><div class="feature-marker" style="background:#0b0b0b"></div><h3>Staff Workspace & Attendance</h3><p>Staff profiles, commission tracking, attendance logs, shift management, and performance metrics.</p></div><div class="feature-card"><div class="feature-marker" style="background:#d4af37"></div><h3>Clients, Memberships & Loyalty</h3><p>CRM with client history, membership plans, loyalty points, gift cards, and automated marketing campaigns.</p></div><div class="feature-card"><div class="feature-marker" style="background:#0b0b0b"></div><h3>Inventory & Stock Control</h3><p>Real-time stock tracking, low stock alerts, purchase orders, and inventory across multiple branches.</p></div><div class="feature-card"><div class="feature-marker" style="background:#d4af37"></div><h3>Marketing & Automations</h3><p>Email and SMS campaigns, automated follow-ups, promotional offers, and customer segmentation.</p></div><div class="feature-card"><div class="feature-marker" style="background:#0b0b0b"></div><h3>Reports & Analytics</h3><p>Revenue reports, staff performance, client trends, branch comparisons, and custom date range analytics.</p></div><div class="feature-card"><div class="feature-marker" style="background:#d4af37"></div><h3>AI Command Center</h3><p>AI-powered insights, capacity forecasting, retention intelligence, and smart business recommendations.</p></div></div></div></section>

<!-- AI Section -->
<section class="section ai-section" id="ai"><div class="container"><div class="section-head"><h2>AI Command Center</h2><p>Enterprise-grade artificial intelligence built for beauty business management.</p></div><div class="ai-grid"><div class="ai-card"><div class="ai-icon ai-icon-insights"></div><h3>AI Insights</h3><p>Real-time business intelligence with anomaly detection and trend analysis across all operations.</p></div><div class="ai-card"><div class="ai-icon ai-icon-forecast"></div><h3>Capacity Forecast</h3><p>Predict demand, optimize staff scheduling, and maximize revenue with ML-based forecasting.</p></div><div class="ai-card"><div class="ai-icon ai-icon-staff"></div><h3>Staff Performance Intelligence</h3><p>Measure productivity, service quality, and client satisfaction with advanced analytics.</p></div><div class="ai-card"><div class="ai-icon ai-icon-retention"></div><h3>Retention Recommendations</h3><p>Identify at-risk clients, suggest re-engagement campaigns, and improve lifetime value.</p></div><div class="ai-card"><div class="ai-icon ai-icon-health"></div><h3>Business Health Monitoring</h3><p>Real-time dashboard of KPIs with automated alerts for revenue, utilization, and growth metrics.</p></div><div class="ai-card"><div class="ai-icon ai-icon-actions"></div><h3>Smart Owner Actions</h3><p>AI recommends actionable steps to grow revenue, reduce costs, and improve client experience.</p></div></div></div></section>

<!-- Modules -->
<section class="section modules-section" id="modules"><div class="container"><div class="section-head"><h2>All modules included</h2><p>Every tool you need, integrated out of the box.</p></div><div class="modules-grid"><span class="module-chip">Calendar</span><span class="module-chip">Bookings</span><span class="module-chip">Clients</span><span class="module-chip">Staff</span><span class="module-chip">Services</span><span class="module-chip">POS</span><span class="module-chip">Inventory</span><span class="module-chip">Reports</span><span class="module-chip">Marketing</span><span class="module-chip">Automations</span><span class="module-chip">Payments</span><span class="module-chip">Invoices</span><span class="module-chip">Memberships</span><span class="module-chip">Wallet</span><span class="module-chip">Gift Cards</span><span class="module-chip">Loyalty</span><span class="module-chip">Forms</span><span class="module-chip">Online Profile</span><span class="module-chip">Customer Portal</span><span class="module-chip">Branches</span><span class="module-chip">Resources</span><span class="module-chip">Reputation</span><span class="module-chip">Surveys</span><span class="module-chip">Audit Logs</span><span class="module-chip">Data Export</span></div></div></section>

<!-- Business Types -->
<section class="section biz-section" id="business-types"><div class="container"><div class="section-head"><h2>Built for every beauty business</h2><p>Purpose-built solutions for different business models.</p></div><div class="biz-grid"><div class="biz-card"><div class="biz-icon bi-hair"></div><h3>Hair Salons</h3><p>Complete booking, POS, and client management for hair salons of any size.</p></div><div class="biz-card"><div class="biz-icon bi-beauty"></div><h3>Beauty Salons</h3><p>Manage services, products, and memberships for beauty and skincare businesses.</p></div><div class="biz-card"><div class="biz-icon bi-spa"></div><h3>Spas</h3><p>Package management, resource scheduling, and wellness program support.</p></div><div class="biz-card"><div class="biz-icon bi-barber"></div><h3>Barber Shops</h3><p>Fast booking, walk-in management, and retail inventory for barbers.</p></div><div class="biz-card"><div class="biz-icon bi-nail"></div><h3>Nail Studios</h3><p>Service catalog, time-based pricing, and client preference tracking.</p></div><div class="biz-card"><div class="biz-icon bi-clinic"></div><h3>Beauty Clinics</h3><p>Medical-grade scheduling, consent forms, and treatment history tracking.</p></div><div class="biz-card biz-card-wide"><div class="biz-icon bi-chain"></div><h3>Multi-branch Chains</h3><p>Centralized management with branch-level reporting, inventory, and staff control.</p></div></div></div></section>

<!-- Final CTA -->
<section class="cta-section"><div class="container"><div class="cta-box"><h2>Run your entire beauty business from one AI-powered platform.</h2><div class="cta-actions"><a routerLink="/login" class="btn btn-primary btn-lg">Login to Dashboard</a><a routerLink="/book-online" class="btn btn-secondary btn-lg">Open Booking Page</a></div></div></div></section>`,
  styles:[`
/* Hero */
.hero{padding:120px 0 80px;overflow:hidden}.hero-grid{display:grid;grid-template-columns:1fr 1fr;gap:64px;align-items:center}.hero-badge{display:inline-flex;padding:8px 20px;background:var(--soft);border-radius:100px;font-size:13px;font-weight:600;letter-spacing:.02em;margin-bottom:20px;border:1px solid var(--border)}h1{font-size:clamp(36px,4.5vw,56px);line-height:1.08;margin:0 0 20px;font-weight:900;letter-spacing:-.03em}.hero-sub{font-size:18px;line-height:1.6;color:var(--muted);margin:0 0 16px;max-width:520px}.hero-trust{font-size:14px;color:var(--muted);margin-bottom:28px;padding:12px 0;border-top:1px solid var(--border);border-bottom:1px solid var(--border)}.hero-actions{display:flex;gap:14px;flex-wrap:wrap}

/* Dashboard Preview */
.hero-visual{position:relative}.dash-preview{background:var(--soft);border-radius:28px;padding:24px;border:1px solid var(--border);box-shadow:0 32px 80px rgba(0,0,0,.08)}.dash-header{display:flex;align-items:center;gap:8px;margin-bottom:20px;padding-bottom:16px;border-bottom:1px solid var(--border)}.dash-dot{width:10px;height:10px;border-radius:50%;background:#ddd}.dash-dot:first-child{background:#ef4444}.dash-dot:nth-child(2){background:#f59e0b}.dash-dot:nth-child(3){background:#22c55e}.dash-label{margin-left:auto;font-size:12px;font-weight:600;color:var(--muted);text-transform:uppercase;letter-spacing:.05em}.dash-grid{display:grid;grid-template-columns:1fr 1fr;gap:12px;margin-bottom:16px}.dash-card{background:white;border-radius:16px;padding:16px;display:flex;align-items:flex-start;gap:12px;border:1px solid var(--border);transition:all .2s}.dash-card:hover{border-color:#d4d4d4;box-shadow:0 4px 16px rgba(0,0,0,.04);transform:translateY(-2px)}.dash-card-icon{width:40px;height:40px;border-radius:12px;flex-shrink:0;position:relative}.bookings-icon{background:linear-gradient(135deg,#0b0b0b,#333)}.bookings-icon::after{content:'';position:absolute;top:50%;left:50%;transform:translate(-50%,-50%);width:18px;height:18px;border:2px solid white;border-radius:4px}.revenue-icon{background:linear-gradient(135deg,#d4af37,#f0d68a)}.revenue-icon::after{content:'$';position:absolute;top:50%;left:50%;transform:translate(-50%,-50%);font-size:18px;font-weight:900;color:#0b0b0b}.staff-icon{background:linear-gradient(135deg,#0b0b0b,#555)}.staff-icon::after{content:'';position:absolute;top:50%;left:50%;transform:translate(-50%,-50%);width:16px;height:16px;border-radius:50%;border:2px solid white}.ai-icon{background:linear-gradient(135deg,#d4af37,#e8c84a)}.ai-icon::after{content:'AI';position:absolute;top:50%;left:50%;transform:translate(-50%,-50%);font-size:12px;font-weight:900;color:#0b0b0b}.retention-icon{background:linear-gradient(135deg,#0b0b0b,#444)}.retention-icon::after{content:'%';position:absolute;top:50%;left:50%;transform:translate(-50%,-50%);font-size:16px;font-weight:900;color:white}.dash-card-body{flex:1;min-width:0}.dash-card-label{display:block;font-size:12px;font-weight:500;color:var(--muted);margin-bottom:2px}.dash-card-value{display:block;font-size:20px;font-weight:800;letter-spacing:-.02em}.dash-card-change{font-size:11px;font-weight:600}.dash-card-change.up{color:#22c55e}.dash-card-text{font-size:11px;color:var(--muted)}.dash-bar{display:grid;gap:12px;padding-top:16px;border-top:1px solid var(--border)}.dash-bar-item{display:flex;align-items:center;gap:12px;font-size:13px;font-weight:500}.dash-bar-track{flex:1;height:8px;background:#e5e7eb;border-radius:4px;overflow:hidden}.dash-bar-fill{height:100%;background:linear-gradient(90deg,var(--black),#555);border-radius:4px;transition:width 1s}

/* Trust Bar */
.trust-bar{padding:32px 0;border-top:1px solid var(--border);border-bottom:1px solid var(--border);background:var(--soft)}.trust-logos{display:flex;justify-content:center;align-items:center;gap:48px;flex-wrap:wrap}.trust-logos span{font-size:14px;font-weight:600;color:var(--muted);letter-spacing:.02em}

/* Section Headers */
.section-head{text-align:center;max-width:640px;margin:0 auto 56px}.section-head h2{font-size:clamp(28px,3vw,40px);font-weight:900;letter-spacing:-.03em;margin:0 0 12px;line-height:1.1}.section-head p{font-size:17px;color:var(--muted);line-height:1.6;margin:0}

/* Features Grid */
.features-grid{display:grid;grid-template-columns:repeat(4,1fr);gap:20px}.feature-card{background:white;border:1px solid var(--border);border-radius:20px;padding:28px 24px;transition:all .3s;cursor:default}.feature-card:hover{border-color:#d4d4d4;box-shadow:0 12px 40px rgba(0,0,0,.06);transform:translateY(-4px)}.feature-marker{width:32px;height:4px;border-radius:2px;margin-bottom:18px}.feature-card h3{font-size:16px;font-weight:800;margin:0 0 10px;letter-spacing:-.01em}.feature-card p{font-size:14px;line-height:1.6;color:var(--muted);margin:0}

/* AI Section */
.ai-section{background:var(--soft);border-top:1px solid var(--border);border-bottom:1px solid var(--border)}.ai-grid{display:grid;grid-template-columns:repeat(3,1fr);gap:20px}.ai-card{background:white;border:1px solid var(--border);border-radius:20px;padding:32px 28px;transition:all .3s;cursor:default}.ai-card:hover{border-color:#d4d4d4;box-shadow:0 12px 40px rgba(0,0,0,.06);transform:translateY(-4px)}.ai-icon{width:48px;height:48px;border-radius:14px;margin-bottom:20px;position:relative;background:var(--black)}.ai-icon::after{position:absolute;top:50%;left:50%;transform:translate(-50%,-50%);font-size:20px;font-weight:700;color:var(--gold)}.ai-icon-insights::after{content:'AI'}.ai-icon-forecast::after{content:'⇈'}.ai-icon-staff::after{content:'⬡'}.ai-icon-retention::after{content:'↗'}.ai-icon-health::after{content:'♦'}.ai-icon-actions::after{content:'→'}.ai-card h3{font-size:18px;font-weight:800;margin:0 0 10px}.ai-card p{font-size:14px;line-height:1.6;color:var(--muted);margin:0}

/* Modules */
.modules-section{background:white}.modules-grid{display:flex;flex-wrap:wrap;justify-content:center;gap:12px;max-width:900px;margin:0 auto}.module-chip{display:inline-flex;padding:12px 24px;background:var(--soft);border:1px solid var(--border);border-radius:12px;font-size:14px;font-weight:600;transition:all .2s;cursor:default}.module-chip:hover{background:var(--black);color:white;border-color:var(--black);transform:translateY(-2px)}

/* Business Types */
.biz-section{background:var(--soft);border-top:1px solid var(--border)}.biz-grid{display:grid;grid-template-columns:repeat(3,1fr);gap:20px}.biz-card{background:white;border:1px solid var(--border);border-radius:20px;padding:28px;text-align:center;transition:all .3s;cursor:default}.biz-card:hover{border-color:#d4d4d4;box-shadow:0 12px 40px rgba(0,0,0,.06);transform:translateY(-4px)}.biz-card-wide{grid-column:1/-1;max-width:400px;justify-self:center;width:100%}.biz-icon{width:48px;height:48px;border-radius:14px;margin:0 auto 16px;background:var(--black);position:relative}.biz-icon::after{position:absolute;top:50%;left:50%;transform:translate(-50%,-50%);font-size:20px;color:var(--gold)}.bi-hair::after{content:'✧'}.bi-beauty::after{content:'✦'}.bi-spa::after{content:'◈'}.bi-barber::after{content:'◇'}.bi-nail::after{content:'◎'}.bi-clinic::after{content:'⊕'}.bi-chain::after{content:'⊞'}.biz-card h3{font-size:17px;font-weight:800;margin:0 0 8px}.biz-card p{font-size:14px;line-height:1.6;color:var(--muted);margin:0}

/* CTA */
.cta-section{padding:96px 0}.cta-box{background:var(--black);border-radius:32px;padding:72px 48px;text-align:center;position:relative;overflow:hidden}.cta-box h2{font-size:clamp(28px,3.5vw,44px);font-weight:900;color:white;margin:0 0 32px;line-height:1.1;letter-spacing:-.03em;max-width:700px;margin-left:auto;margin-right:auto}.cta-actions{display:flex;gap:16px;justify-content:center;flex-wrap:wrap}.cta-box .btn-primary{background:var(--gold);color:var(--black);border-color:var(--gold)}.cta-box .btn-primary:hover{background:white;color:var(--black);border-color:white}.cta-box .btn-secondary{background:transparent;color:white;border-color:rgba(255,255,255,.3)}.cta-box .btn-secondary:hover{background:rgba(255,255,255,.1);border-color:rgba(255,255,255,.5)}

/* Responsive */
@media(max-width:1024px){.features-grid{grid-template-columns:repeat(2,1fr)}.ai-grid{grid-template-columns:repeat(2,1fr)}}
@media(max-width:768px){.hero{padding:80px 0 60px}.hero-grid{grid-template-columns:1fr;gap:40px}.hero-sub{max-width:100%}.hero-actions{flex-direction:column}.hero-visal{margin-top:0}.dash-grid{grid-template-columns:1fr}.trust-logos{gap:24px}.features-grid{grid-template-columns:1fr}.ai-grid{grid-template-columns:1fr}.biz-grid{grid-template-columns:1fr}.cta-box{padding:48px 24px;border-radius:24px}.cta-actions{flex-direction:column}}
@media(max-width:480px){.hero{padding:60px 0 40px}h1{font-size:clamp(28px,8vw,36px)}}
  `]
})
export class HomeComponent{} 
